primary_region = "nrt"

[build]
image = "ghcr.io/making/vault-s3"

[http_service]
  internal_port = 8200
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
